{% set version = "2.10-2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rnetcdf
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/RNetCDF_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RNetCDF/RNetCDF_{{ version }}.tar.gz
  sha256: 40397fa8f773779876d9db356d47781c88eab35902c663b59d230fb780269352

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  # Checking windows to see if it passes. Uncomment the line if it fails.
  # skip: true  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - libnetcdf
    - udunits2
  run:
    - r-base

test:
  commands:
    - $R -e "library('RNetCDF')"           # [not win]
    - "\"%R%\" -e \"library('RNetCDF')\""  # [win]

about:
  home: https://www.unidata.ucar.edu/software/netcdf/
  dev_url: https://github.com/mjwoods/RNetCDF
  license: GPL-2.0-or-later
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
    - LICENSE
  summary: An interface to the 'NetCDF' file formats designed by Unidata for efficient storage of array-oriented scientific data and descriptions. Most capabilities of 'NetCDF' version 4 are supported. Optional conversions of time units are enabled by 'UDUNITS' version 2, also from Unidata.

extra:
  recipe-maintainers:
    - ocefpaf
    - marcelotrevisani
    - conda-forge/r
