travis:
  secure:
    BINSTAR_TOKEN: AgdsC4T99PihAqWok82UjxktGCExaBicQTq1P9irXUBZxF1gQD60FiKpFnDl+8guQ01Ikdj8bVUaLB/2xM0/NDDYkl5lP1MfaHLvd9HtZ+ZcRoOTf2bGj9R7SfqcwTPZ5iSXJagFU7FbJgYY8cEUWZv2KSYBdj1Frz8sAtHh9CxX1vO5iF2aspdMYXZphOUx/EoTe62aun9ilBqWE+Ch5xdUax+4COtaQYyImU6RFlcG3E+3vsiNgymIFUbd1uKECsYaAr/497Y/GUwlxb3L0/0NV9N61jMmsuHDNV1OoOxmSzbhiw8cEO2amTDcajseGb7EuJkUDErqH2wcyW9JHjHNfwU1k/vzdBkTaYlVqVaV8VujtZgcef4/NW/h1j9hLjBJ8DBGDzCXepsqAYZgMvaHCAWoEeEBWLnCxjNMdNksAwukvGBGL+kACDwU4f4DyJFzc0mNVOX97ww6DZzBB7k0txj/+UA0l8gAcW7QXAsC3GKmGO0U4d+h65S3Zj20X+A/G8o4DZi9oODU09PvIqv/qts4Ja90lVwlUdrM+eRGdZqHVT4Nr2E1q9YtGInDbh4x0VDX/pvadTCfTuDPaO7PdGT62mmO4eWQ+zGojOXqbl+I/fDrptW97uzUlFJFifJLFBQ8B3w3bl5j6lEFRa1bw3joyWvNJYHE4QGw9NU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
